# Permalinks format of each content section
post = "/p/:year/:month/:slugorcontentbasename/"
page = "/:slugorcontentbasename/"
artwork = "/art/:year/:month/:slugorcontentbasename/"
[section]
artwork = "/art"
